### ISSUE TITLE
issue installing bitclust

### ISSUE THREAD

**Issue by claudiamejias** [rglez/bitclust#2]
Collecting bitclust
  Using cached https://files.pythonhosted.org/packages/c2/0f/d5f5a7b552a487653f58b466ec959cbc4e78db33507b7153867683130fc1/bitclust-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gwRBLa/bitclust/setup.py", line 8, in <module>
        README = (HERE / "README.md").read_text()
    AttributeError: 'PosixPath' object has no attribute 'read_text'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gwRBLa/bitclust/

I already have mdtraj installed
I'm using python2.7 and pip version according to it

**Comment by claudiamejias** [comment]
SOLVED IT!!!! I needed python3 for the proper installation
